### ISSUE TITLE
package installation error

### ISSUE THREAD

**Issue by arnaou** [TUHH-TVT/openCOSMO-RS_py#1]
Hi,

I was trying to install the package using 
pip install opencosmorspy

however I get the following error:

ERROR: Could not find a version that satisfies the requirement opencosmorspy (from versions: none)
ERROR: No matching distribution found for opencosmorspy

I am using a conda environment with python 3.9.

Hope you can provide some assistance

**Comment by simonmb** [comment]
Is this on windows or linux? Or did you manage to solve the problem?

**Comment by arnaou** [comment]
Managed to install it directly from GitHub not through pip but the documentation of how to integrate ORCA is lacking as well as other requirements.
