### ISSUE TITLE
Temperature dependance

### ISSUE THREAD

**Issue by KSTU** [TUHH-TVT/openCOSMO-RS_py#10]
I calculate the activity coefficients of mixtures (for example, I took ethanol and water). However, in this program, the values ​​of the activity coefficients do not depend on temperature, although they should.
Maybe I'm doing something wrong?

**Comment by simonmb** [comment]
Hi @KSTU,
what is the code you are using? Without it, unfortunately, I would not be able to help you.

**Comment by KSTU** [comment]
Sorry, my mistake.

**Comment by simonmb** [comment]
Ok
